### ISSUE TITLE
erb-gen doesn't seem to work, its probably something i'm doing wrong.

### ISSUE THREAD

**Issue by DetroitWhiskey136** [htdangkhoa/erb#52]
Even if I just install the repo through git the npm scripts for the most part error about various things also the cli isn't working at all if I could get some assistance I would appreciate it.

__CLI__
![image](https://user-images.githubusercontent.com/45453611/92999297-9cda0780-f4d4-11ea-80ae-9c6ebce4dcf5.png)

__NODE Version__
![image](https://user-images.githubusercontent.com/45453611/92999343-f93d2700-f4d4-11ea-8834-ba84c3eac9a4.png)

__ YARN DEV __
![image](https://user-images.githubusercontent.com/45453611/92999362-17a32280-f4d5-11ea-8d68-66c9582ef07a.png)

**Comment by DetroitWhiskey136** [comment]
if you need any other info please let me know

**Comment by htdangkhoa** [comment]
Hi, @DetroitWhiskey136 can you re-up your images, I can't see it.

**Comment by DetroitWhiskey136** [comment]
![92999297-9cda0780-f4d4-11ea-80ae-9c6ebce4dcf5](https://user-images.githubusercontent.com/45453611/93027950-66c88080-f5c5-11ea-8b98-cc1e8c69888a.png)
![92999343-f93d2700-f4d4-11ea-8834-ba84c3eac9a4](https://user-images.githubusercontent.com/45453611/93027951-67f9ad80-f5c5-11ea-831c-2dd2c73e5994.png)
![92999362-17a32280-f4d5-11ea-8d68-66c9582ef07a](https://user-images.githubusercontent.com/45453611/93027952-69c37100-f5c5-11ea-8117-6a494edc6d1c.png)

**Comment by htdangkhoa** [comment]
Hi @DetroitWhiskey136 , thanks for your report. You can try to install as `administrator` or (`sudo`).

```shell
(sudo) npm install -g express-react-boilerplate
```

**Comment by DetroitWhiskey136** [comment]
that fixed the ability to use erb-gen however yarn dev still fails at the clean script stating
```
G:\Development\Javascript\erb-testing>yarn dev
yarn run v1.22.5$ del dist && npm run clean
Could Not Find G:\Development\Javascript\erb-testing\dist

> express-react-boilerplate@1.0.0 clean G:\Development\Javascript\erb-testing
> del "public/*" "!public/assets" "!public/locales" "!public/robots.txt" "!public/googledb37d62693032295.html"

The system cannot find the path specified.
npm ERR! code ELIFECYCLEnpm ERR! errno 3
npm ERR! express-react-boilerplate@1.0.0 clean: `del "public/*" "!public/assets" "!public/locales" "!public/robots.txt" "!public/googledb37d62693032295.html"`
npm ERR! Exit status 3
npm ERR! npm ERR! Failed at the express-react-boilerplate@1.0.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Danno3817\AppData\Roaming\npm-cache\_logs\2020-09-15T04_24_34_735Z-debug.log
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by DetroitWhiskey136** [comment]
i'm probably missing something really silly tbh.

**Comment by DetroitWhiskey136** [comment]
like, is this designed with windows os in mind? does it even matter?

**Comment by DetroitWhiskey136** [comment]
i guess that wouldn't matter with the scripts given windows has bash baked in now
