### ISSUE TITLE
Cant run on production. Npm start fails locally

### ISSUE THREAD

**Issue by webface** [htdangkhoa/erb#53]
when I build and run npm start it stalls...
```
> env-cmd -e production node dist/index.js

Starting the production server...
```

**Comment by htdangkhoa** [comment]
> when I build and run npm start it stalls...
> 
> ```
> > env-cmd -e production node dist/index.js
> 
> Starting the production server...
> ```

Hi @webface in my case when I see this message, the server already started. Can you describe more about this issue?

**Comment by webface** [comment]
@htdangkhoa sorry it does run locally. When I deployed to aws however it could not build and run successfully. The process logged as taking as hour and it crashed my server

**Comment by htdangkhoa** [comment]
> @htdangkhoa sorry it does run locally. When I deployed to aws however it could not build and run successfully. The process logged as taking as hour and it crashed my server

Can you share with me the error log?
